const LOAD_CART = 'LOAD_CART';
const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const EMPTY_CART = 'EMPTY_CART';

export { LOAD_CART, ADD_TO_CART, REMOVE_FROM_CART, EMPTY_CART };
